

import { Geist, Geist_Mono } from "next/font/google";
import "@/style/globals.css";
import Link from "next/link";
import DetailTitle from "@/components/detail-title";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <div className="bg-[#F5F7F8]">
                <div className="w-[70%] mx-auto py-14">
                    <DetailTitle/>
                    <div>
                        {children}
                    </div>
                </div>
            </div>
      </body>

    </html>
  );
}
