import { Geist, Geist_Mono } from "next/font/google";
import "@/style/globals.css";
import DashboardSidebar from "@/components/sidebar/sidebar";
import SearchNavbar from "@/components/search-navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="grid grid-cols-12 max-h-screen overflow-hidden">
          <aside className="col-span-3 bg-slate-400">
            <DashboardSidebar />
          </aside>
          <section className="col-span-9 bg-gray-300 p-10">
            <div>
              <SearchNavbar />
            </div>
            <div className="bg-[#FFFFFF] rounded-3xl py-8 px-10 mt-6 max-h-screen overflow-auto scrollbar-hide">
              {children}
            </div>
          </section>
        </div>
      </body>

    </html>
  );
}
